apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: plx3kxl34-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: plx3kxl34-go 
  name: plx3kxl34-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: plx3kxl34-go 
